[package]
name = "majestyOS"
version = "0.1.0"
edition = "2018"
authors = ["Saptarshi <mail@sbk2k1.in>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"