[package]
name = "majestyOS"
version = "0.1.0"
edition = "2018"
authors = ["Saptarshi <mail@sbk2k1.in>"]

[dependencies]
bootloader = "0.9.23"
spin = "0.9.0"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]